[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

build_flags =
    -DCORE_DEBUG_LEVEL=0

lib_deps =
    mikalhart/TinyGPSPlus
    adafruit/Adafruit MPU6050
    adafruit/Adafruit Unified Sensor
    olikraus/U8g2
    adafruit/Adafruit BMP280 Library
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306